const chemical_supplies = [
  {
    id: 1,
    chemicalName: "Caustic Potash",
    vendor: "LG Chen",
    density: 3525.92,
    viscosity: 69.63,
    packaging: "Bag",
    packSize: 100,
    unit: "kg",
    quantity: 6495.18,
  },

  {
    id: 2,
    chemicalName: "Ferric Nitrate",
    vendor: "Formosa",
    density: 364.04,
    viscosity: 14.9,
    packaging: "Bag",
    packSize: 105,
    unit: "kg",
    quantity: 4154.33,
  },

  {
    id: 3,
    chemicalName: "Dimethylaminopropylamino",
    vendor: "LG Chen",
    density: 8435.37,
    viscosity: 12.62,
    packaging: "Barrel",
    packSize: 75,
    unit: "l",
    quantity: 5964.61,
  },

  {
    id: 4,
    chemicalName: "n-Pentane",
    vendor: "Sinopec",
    density: 4535.26,
    viscosity: 66.76,
    packaging: "N/A",
    packSize: "N/A",
    unit: "t",
    quantity: 6272.54,
  },
  {
    id: 5,
    chemicalName: "b-Heptane",
    vendor: "Dizene",
    density: 5435.26,
    viscosity: 46.76,
    packaging: "Bag",
    packSize: "60",
    unit: "t",
    quantity: 8972.54,
  },
  {
    id: 6,
    chemicalName: "Oxythylaminopro",
    vendor: "MG Shein",
    density: 4835.37,
    viscosity: 21.62,
    packaging: "Barrel",
    packSize: 75,
    unit: "l",
    quantity: 6564.61,
  },
  {
    id: 7,
    chemicalName: "Lament Nitrate",
    vendor: "Formosa",
    density: 264.04,
    viscosity: 64.9,
    packaging: "N/A",
    packSize: "N/A",
    unit: "kg",
    quantity: 1454.33,
  },
  {
    id: 8,
    chemicalName: "Benzene Potash",
    vendor: "ABC pharm",
    density: 7525.92,
    viscosity: 99.63,
    packaging: "Bag",
    packSize: 110,
    unit: "kg",
    quantity: 9495.18,
  },
  {
    id: 9,
    chemicalName: "Aqustic Nitrate",
    vendor: "PQ Chen",
    density: 3125.92,
    viscosity: 49.63,
    packaging: "Barrel",
    packSize: 100,
    unit: "l",
    quantity: 4695.18,
  },

  {
    id: 10,
    chemicalName: "Fenzene Pitrate",
    vendor: "Wen Che",
    density: 164.04,
    viscosity: 19.9,
    packaging: "Bag",
    packSize: 125,
    unit: "kg",
    quantity: 7554.33,
  },

  {
    id: 11,
    chemicalName: "Methylaminopro",
    vendor: "VT Co.",
    density: 5435.37,
    viscosity: 16.62,
    packaging: "Barrel",
    packSize: 175,
    unit: "l",
    quantity: 964.61,
  },

  {
    id: 12,
    chemicalName: "Glucoform",
    vendor: "Tipec",
    density: 8535.26,
    viscosity: 86.76,
    packaging: "N/A",
    packSize: "N/A",
    unit: "t",
    quantity: 8272.54,
  },
  {
    id: 13,
    chemicalName: "Yethylaminopro",
    vendor: "Tipec",
    density: 3035.37,
    viscosity: 75.62,
    packaging: "Bag",
    packSize: 75,
    unit: "kg",
    quantity: 564.61,
  },

  {
    id: 14,
    chemicalName: "Xennex",
    vendor: "Formosa",
    density: 5335.26,
    viscosity: 36.76,
    packaging: "Bag",
    packSize: 90,
    unit: "t",
    quantity: 1272.54,
  },

  {
    id: 15,
    chemicalName: "Ethanyol",
    vendor: "VT Co.",
    density: 1335.26,
    viscosity: 26.76,
    packaging: "Barrel",
    packSize: 50,
    unit: "t",
    quantity: 572.54,
  },
];
